### ISSUE TITLE
Содержимое ветки

### ISSUE THREAD

**Issue by ruslan1984** [nickovchinnikov/react-js-tutorial#77]
Внутри ветки должно быть только то, что соответсвует данной теме. 
Не должно быть директорий lessen11, lessen12... Весь код хранить в соответствующей директории,  и только то что касается тематики урока.

**Comment by nickovchinnikov** [comment]
Смотри содержимое pull request, в diff подливается только то, что касается темы урока

**Comment by ruslan1984** [comment]
> Смотри содержимое pull request, в diff подливается только то, что касается темы урока
У нас задание к ДЗ задание, оставить 2 коммита. По поводу pr знаю, частенько смотрю, но ветки оформить по названиям еще круче будет.

**Comment by nickovchinnikov** [comment]
@ruslan1984 не обращайте внимание на ветки и их название, в репозитории эта логики не будет работать, в общем

**Comment by ruslan1984** [comment]
@nickovchinnikov спорить не могу с вами. Но в pr только кусок кода, там нет общей картины. Приходиться все разгребать. А если в отдельной ветке будет только, то что касается темы с pr от прошлой ветки, что бы видеть что поменялось, тогда будет шикарно. Человеку который только только начал все это изучать, не просто  ориентироваться в этом многообразии. Я не настаиваю что бы что то меняли, я задание из ДЗ выполняю https://prnt.sc/v2emxa. Этого достаточно для ДЗ? Или я не правильно понял задание?

**Comment by ruslan1984** [comment]
@nickovchinnikov даже не через ветки, а тэги подобное можно реализовать
